M48
; DRILL file KiCad 10.0.5 date NORMALIZED
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,NORMALIZED
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.350
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.500
%
G90
G05
T1
X13.0Y-10.0
X15.0Y-20.0
X17.0Y-10.0
T2
X10.0Y-10.0
X10.0Y-20.0
X20.0Y-10.0
X20.0Y-20.0
M30
