M48
; DRILL file KiCad 10.0.5 date NORMALIZED
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,NORMALIZED
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.350
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.600
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.650
%
G90
G05
T1
X15.0Y-5.0
T2
X15.0Y-8.0
T3
X15.0Y-11.0
T4
X15.0Y-14.0
M30
